import pandas as pd
import numpy as np

class Order:
    """
    Encapsulates all trade parameters generated by the Risk Engine.
    """
    def __init__(self, direction: str, entry_price: float, sl_price: float, tp_price: float = None, 
                 trail_multiplier: float = None, size: float = 1.0, strategy_name: str = "Unknown"):
        self.direction = direction.upper().strip()  # 'BUY' or 'SELL'
        self.entry_price = entry_price
        self.sl_price = sl_price
        self.tp_price = tp_price
        self.trail_multiplier = trail_multiplier
        self.size = size
        self.strategy_name = strategy_name

    def __repr__(self):
        return (f"Order({self.direction} @ {self.entry_price:.5f}, SL: {self.sl_price:.5f}, "
                f"TP: {self.tp_price if self.tp_price else 'None'}, Size: {self.size}, Strat: {self.strategy_name})")


class RiskEngine:
    """
    Manages trade stop placement, profit targets, position sizing, and trailing parameters.
    """
    def __init__(self, risk_fraction: float = 0.01, default_pip_value: float = 1.0):
        self.risk_fraction = risk_fraction
        self.default_pip_value = default_pip_value

    def calculate_order(self, direction: str, current_price: float, atr: float, pip_size: float, 
                        capital: float, sl_multiplier: float, tp_multiplier: float = None, 
                        trail_multiplier: float = None, strategy_name: str = "Unknown",
                        risk_fraction: float = None) -> Order:
        """
        Creates a structured Order with calculated SL, TP, and dynamic lot sizing.
        """
        # Determine SL distance in raw price
        sl_distance = atr * sl_multiplier
        
        if direction.upper() == 'BUY':
            sl_price = current_price - sl_distance
            tp_price = current_price + (atr * tp_multiplier) if tp_multiplier else None
        else:
            sl_price = current_price + sl_distance
            tp_price = current_price - (atr * tp_multiplier) if tp_multiplier else None
            
        # Calculate Risk Sizing:
        use_risk_fraction = risk_fraction if risk_fraction is not None else self.risk_fraction
        risk_usd = capital * use_risk_fraction
        sl_pips = sl_distance / pip_size if pip_size > 0 else 1.0
        
        # Sizing relative to standard pip value
        size = risk_usd / (sl_pips * self.default_pip_value) if sl_pips > 0 else 1.0
        size = max(0.1, round(size, 2))  # Bound size to sensible fractional lots
        
        return Order(
            direction=direction,
            entry_price=current_price,
            sl_price=sl_price,
            tp_price=tp_price,
            trail_multiplier=trail_multiplier,
            size=size,
            strategy_name=strategy_name
        )
